
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Header': typeof import("../components/Header.vue")['default']
    'MobileMenu': typeof import("../components/MobileMenu.vue")['default']
    'NewCustomers': typeof import("../components/NewCustomers.vue")['default']
    'ProfileInfo': typeof import("../components/ProfileInfo.vue")['default']
    'RecentOrders': typeof import("../components/RecentOrders.vue")['default']
    'Reminders': typeof import("../components/Reminders.vue")['default']
    'SalesChart': typeof import("../components/SalesChart.vue")['default']
    'Sidebar': typeof import("../components/Sidebar.vue")['default']
    'SidebarItem': typeof import("../components/SidebarItem.vue")['default']
    'StatusCard': typeof import("../components/StatusCard.vue")['default']
    'TransitionExpand': typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
    'TransitionFade': typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
    'TransitionScale': typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
    'TransitionSlide': typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'HCombobox': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
    'HComboboxLabel': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
    'HComboboxButton': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
    'HComboboxInput': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
    'HComboboxOptions': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
    'HComboboxOption': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
    'HDialog': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
    'HDialogOverlay': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
    'HDialogBackdrop': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
    'HDialogPanel': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
    'HDialogTitle': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
    'HDialogDescription': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
    'HDisclosure': typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
    'HDisclosureButton': typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
    'HDisclosurePanel': typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
    'HFocusTrap': typeof import("../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
    'HListbox': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
    'HListboxLabel': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
    'HListboxButton': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
    'HListboxOptions': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
    'HListboxOption': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
    'HMenu': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
    'HMenuButton': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
    'HMenuItems': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
    'HMenuItem': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
    'HPopover': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
    'HPopoverButton': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
    'HPopoverOverlay': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
    'HPopoverPanel': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
    'HPopoverGroup': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
    'HPortal': typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
    'HPortalGroup': typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
    'HRadioGroup': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
    'HRadioGroupOption': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
    'HRadioGroupLabel': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
    'HRadioGroupDescription': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
    'HSwitchGroup': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
    'HSwitch': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
    'HSwitchLabel': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
    'HSwitchDescription': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
    'HTabGroup': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
    'HTabList': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
    'HTab': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
    'HTabPanels': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
    'HTabPanel': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
    'HTransitionChild': typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
    'HTransitionRoot': typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyMobileMenu': typeof import("../components/MobileMenu.vue")['default']
    'LazyNewCustomers': typeof import("../components/NewCustomers.vue")['default']
    'LazyProfileInfo': typeof import("../components/ProfileInfo.vue")['default']
    'LazyRecentOrders': typeof import("../components/RecentOrders.vue")['default']
    'LazyReminders': typeof import("../components/Reminders.vue")['default']
    'LazySalesChart': typeof import("../components/SalesChart.vue")['default']
    'LazySidebar': typeof import("../components/Sidebar.vue")['default']
    'LazySidebarItem': typeof import("../components/SidebarItem.vue")['default']
    'LazyStatusCard': typeof import("../components/StatusCard.vue")['default']
    'LazyTransitionExpand': typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
    'LazyTransitionFade': typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
    'LazyTransitionScale': typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
    'LazyTransitionSlide': typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyHCombobox': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
    'LazyHComboboxLabel': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
    'LazyHComboboxButton': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
    'LazyHComboboxInput': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
    'LazyHComboboxOptions': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
    'LazyHComboboxOption': typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
    'LazyHDialog': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
    'LazyHDialogOverlay': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
    'LazyHDialogBackdrop': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
    'LazyHDialogPanel': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
    'LazyHDialogTitle': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
    'LazyHDialogDescription': typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
    'LazyHDisclosure': typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
    'LazyHDisclosureButton': typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
    'LazyHDisclosurePanel': typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
    'LazyHFocusTrap': typeof import("../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
    'LazyHListbox': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
    'LazyHListboxLabel': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
    'LazyHListboxButton': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
    'LazyHListboxOptions': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
    'LazyHListboxOption': typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
    'LazyHMenu': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
    'LazyHMenuButton': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
    'LazyHMenuItems': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
    'LazyHMenuItem': typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
    'LazyHPopover': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
    'LazyHPopoverButton': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
    'LazyHPopoverOverlay': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
    'LazyHPopoverPanel': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
    'LazyHPopoverGroup': typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
    'LazyHPortal': typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
    'LazyHPortalGroup': typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
    'LazyHRadioGroup': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
    'LazyHRadioGroupOption': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
    'LazyHRadioGroupLabel': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
    'LazyHRadioGroupDescription': typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
    'LazyHSwitchGroup': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
    'LazyHSwitch': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
    'LazyHSwitchLabel': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
    'LazyHSwitchDescription': typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
    'LazyHTabGroup': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
    'LazyHTabList': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
    'LazyHTab': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
    'LazyHTabPanels': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
    'LazyHTabPanel': typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
    'LazyHTransitionChild': typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
    'LazyHTransitionRoot': typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Header: typeof import("../components/Header.vue")['default']
export const MobileMenu: typeof import("../components/MobileMenu.vue")['default']
export const NewCustomers: typeof import("../components/NewCustomers.vue")['default']
export const ProfileInfo: typeof import("../components/ProfileInfo.vue")['default']
export const RecentOrders: typeof import("../components/RecentOrders.vue")['default']
export const Reminders: typeof import("../components/Reminders.vue")['default']
export const SalesChart: typeof import("../components/SalesChart.vue")['default']
export const Sidebar: typeof import("../components/Sidebar.vue")['default']
export const SidebarItem: typeof import("../components/SidebarItem.vue")['default']
export const StatusCard: typeof import("../components/StatusCard.vue")['default']
export const TransitionExpand: typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
export const TransitionFade: typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
export const TransitionScale: typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
export const TransitionSlide: typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const HCombobox: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
export const HComboboxLabel: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
export const HComboboxButton: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
export const HComboboxInput: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
export const HComboboxOptions: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
export const HComboboxOption: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
export const HDialog: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
export const HDialogOverlay: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
export const HDialogBackdrop: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
export const HDialogPanel: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
export const HDialogTitle: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
export const HDialogDescription: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
export const HDisclosure: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
export const HDisclosureButton: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
export const HDisclosurePanel: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
export const HFocusTrap: typeof import("../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
export const HListbox: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
export const HListboxLabel: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
export const HListboxButton: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
export const HListboxOptions: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
export const HListboxOption: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
export const HMenu: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
export const HMenuButton: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
export const HMenuItems: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
export const HMenuItem: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
export const HPopover: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
export const HPopoverButton: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
export const HPopoverOverlay: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
export const HPopoverPanel: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
export const HPopoverGroup: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
export const HPortal: typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
export const HPortalGroup: typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
export const HRadioGroup: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
export const HRadioGroupOption: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
export const HRadioGroupLabel: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
export const HRadioGroupDescription: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
export const HSwitchGroup: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
export const HSwitch: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
export const HSwitchLabel: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
export const HSwitchDescription: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
export const HTabGroup: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
export const HTabList: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
export const HTab: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
export const HTabPanels: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
export const HTabPanel: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
export const HTransitionChild: typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
export const HTransitionRoot: typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyMobileMenu: typeof import("../components/MobileMenu.vue")['default']
export const LazyNewCustomers: typeof import("../components/NewCustomers.vue")['default']
export const LazyProfileInfo: typeof import("../components/ProfileInfo.vue")['default']
export const LazyRecentOrders: typeof import("../components/RecentOrders.vue")['default']
export const LazyReminders: typeof import("../components/Reminders.vue")['default']
export const LazySalesChart: typeof import("../components/SalesChart.vue")['default']
export const LazySidebar: typeof import("../components/Sidebar.vue")['default']
export const LazySidebarItem: typeof import("../components/SidebarItem.vue")['default']
export const LazyStatusCard: typeof import("../components/StatusCard.vue")['default']
export const LazyTransitionExpand: typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
export const LazyTransitionFade: typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
export const LazyTransitionScale: typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
export const LazyTransitionSlide: typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyHCombobox: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
export const LazyHComboboxLabel: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
export const LazyHComboboxButton: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
export const LazyHComboboxInput: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
export const LazyHComboboxOptions: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
export const LazyHComboboxOption: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
export const LazyHDialog: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
export const LazyHDialogOverlay: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
export const LazyHDialogBackdrop: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
export const LazyHDialogPanel: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
export const LazyHDialogTitle: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
export const LazyHDialogDescription: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
export const LazyHDisclosure: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
export const LazyHDisclosureButton: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
export const LazyHDisclosurePanel: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
export const LazyHFocusTrap: typeof import("../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
export const LazyHListbox: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
export const LazyHListboxLabel: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
export const LazyHListboxButton: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
export const LazyHListboxOptions: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
export const LazyHListboxOption: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
export const LazyHMenu: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
export const LazyHMenuButton: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
export const LazyHMenuItems: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
export const LazyHMenuItem: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
export const LazyHPopover: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
export const LazyHPopoverButton: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
export const LazyHPopoverOverlay: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
export const LazyHPopoverPanel: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
export const LazyHPopoverGroup: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
export const LazyHPortal: typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
export const LazyHPortalGroup: typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
export const LazyHRadioGroup: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
export const LazyHRadioGroupOption: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
export const LazyHRadioGroupLabel: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
export const LazyHRadioGroupDescription: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
export const LazyHSwitchGroup: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
export const LazyHSwitch: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
export const LazyHSwitchLabel: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
export const LazyHSwitchDescription: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
export const LazyHTabGroup: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
export const LazyHTabList: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
export const LazyHTab: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
export const LazyHTabPanels: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
export const LazyHTabPanel: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
export const LazyHTransitionChild: typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
export const LazyHTransitionRoot: typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
